name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
      - name: branch-names
        id: branch-name
        uses: tj-actions/branch-names@v2.2
      - run: sbt coverage +test coverageReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          CI_BRANCH: ${{ steps.branch-name.outputs.current_branch }}
